language: python

python:
    - "3.7"

before_install:
    - if [[ $TRAVIS_PYTHON_VERSION == 2* ]]; then pip install -r requirements.txt; fi
    - if [[ $TRAVIS_PYTHON_VERSION == 3* ]]; then pip install -r requirements.txt; fi
    - pip install coveralls

install:
    - python setup.py -q install

after_success:
    - coveralls
